server:
  port: 6677
spring:
# cloud:
#   sentinel:
#      transport:
#       dashboard: localhost:8080
#        port: 8719
#  profiles:
#    active: dev #开发环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wgp?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: vps.wdf2020.cf
    port: 6379