server:
  port: 9999
spring:
  application:
    name: kafka-provider
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          #zk-nodes: localhost:2181
      binders:
        myMq:
          destination: demo
          content-type: text/plain