server:
  port: 9977
spring:
  application:
    name: mail-service
  mail:
    host: smtp.qq.com
    username: 444@444.com
    password: 123456
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    default-encoding: utf-8
