
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      discovery:
        locator:
          enabled: true
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: url-user # 路由的id,没有规定规则但要求唯一,建议配合服务名
            #匹配后提供服务的路由地址
          uri: lb://user-service
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/user/**,/auth/**
        - id: url-file
          uri: lb://file-service
          predicates:
            - Path=/file/**,/dir/**,/tran/**,/share/**
        - id: url-admin
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
server:
  port: 8000
