server:
  port: 9999
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: file-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wgp?serverTimezone=UTC
    username: root
    password: 123456
    jpa:
      database: mysql
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

hdfs:
  path: hdfs://master:9000
  #  全分布地址
  #  path: hdfs://192.168.88.132:9000
  user: hades

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.lhq.dao: debug