server:
  port: 9999
spring:
  cache:
    cache-names: directoryCache
    type: redis
  application:
    name: file-service
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://localhost:3306/wgp?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  redis:
    host: localhost
    port: 6379
    database: 1

hdfs:
  path: hdfs://master:9000
  #  全分布地址
  #  path: hdfs://192.168.88.132:9000
  user: hades


feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  compression:
    response:
      enabled: true
    request:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000   # 读超时时间
        loggerLevel: FULL # 日志级别