spring:
  application:
    name: file-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        file-extension: yaml
        group: DEV_GROUP
        namespace: Dev
        prefix: file
      server-addr: master:8848