server:
  port: 8889
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: admin-service
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  compression:
    response:
      enabled: true
    request:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000   # 读超时时间
        loggerLevel: FULL # 日志级别